from bidding_tree import bids
import pytest

testcases = [
    ("you open", [], 12, 3, 5, 2, 0, "1Hs", "Normal_5card"),
    ("you open pass", [], 11, 0, 0, 5, 0, "pass", "open_pass"),
    ("you open preemtif", [], 8, 7, 0, 0, 0, '3Ss', "preemtif3"),
    ("you open 1SA", [], 16, 5, 2, 3, 3, '1SA', "1SA_opening"),
    ("you open 1Cs", [], 13, 4, 4, 3, 2, '1Cs', "1Cs_opening"),
    ("you open 2SA", [], 21, 5, 2, 3, 4, '2SA', '2SA_opening'),
    ("you open 2Cs w pts", [], 25, 0, 0, 0, 0, '2Cs',"noexplain"),
    ("you open 2Cs", [], 16, 7, 0, 0, 0, '2Cs',"noexplain"),
    ("you open 2Hs", [], 0, 0, 6, 0, 0, '2Hs',"noexplain"),
    ("you open 2SA", [], 21, 5, 3, 3, 2, '2SA',"noexplain"),
    ("jacoby", ["1SA", "pass"], 0, 0, 5, 0, 0, '2Ds',"noexplain"),
    ("stayman", ["1SA", "pass"], 8, 4, 0, 0, 0, '2Cs',"noexplain"),
    ("answer to Stayman", ["1SA", "pass", "2♣", "pass"], 16, 0, 4, 0, 0, '2Hs',"noexplain"),
    ("answer 2SA to 1SA", ["1SA", "pass"], 8, 0, 0, 4, 0, '2SA',"noexplain"),
    ("answer 3SA to 1SA", ["1SA", "pass"], 10, 0, 0, 0, 0, '3SA',"noexplain"),
    ("answer to partner lvl 1", ["1Cs", "pass"], 20, 0, 4, 0, 0, '1Hs',"noexplain"),
    ("preemptief3", [], 8, 0, 7, 0, 0,'3Hs', "preemtif3"),
    ("answer pass", ["1Ss", "pass"], 2, 4, 0, 0, 0, 'pass',"noexplain"),
    ("informatiedoublet", ['1Ss'], 13, 3, 4, 3, 3, 'X',"noexplain"),
    ("answer 1SA 6 card", ['1SA', 'pass', '2hs', 'pass', '2Ss', 'pass'], 11, 6, 0, 0, 0, '4Ss',"noexplain"),
    ("volgbod", ['1Ds'], 9, 0, 5, 0, 0, "1Hs","noexplain"),
    ("preemptief volgbod", ['1Ds'], 8, 0, 7, 0, 0, "3Hs","noexplain"),
    ("preemptief4", [], 3, 0, 0, 0, 8, "4Cs","noexplain"),
    ("weak2", [], 8, 0, 0, 6, 0, "2Ds","noexplain"),
    ("invite3", ["pass", "1Hs", "pass"], 10, 5, 3, 2, 2, "3Hs","noexplain"),
    ("acceptinvite3", ['1Hs', 'pass', '3Hs', 'pass'], 15, 5, 0, 0, 0, '4Ss',"noexplain"),
    ('passto2sa', ['2sa', "pass"], 2, 0, 0, 0, 4, "pass","noexplain"),
    ('roundpass', ["pass", "pass", "pass"], 11, 0, 0, 5, 0, "pass", 'rondpass'),
    ('autogenerated', ['1♣', 'pass'], 10, 2, 4, 2, 5, '???',"noexplain"),
    ('autogenerated', ['1♣', 'pass'], 10, 5, 4, 2, 2, '???',"noexplain"),
    ('autogenerated', ['pass', '1♠', 'pass'], 0, 3, 8, 1, 1, '???',"noexplain"),
    ('autogenerated', ['pass', 'pass', 'pass'], 20, 3, 3, 6, 1, '???',"noexplain"),
    ('veelpunten', ['pass'], 24, 2, 4, 5, 2, '2Cs',"noexplain"),
    ('matchgevonden', ['1♥', 'pass'], 15, 0, 5, 5, 3, '4Hs',"noexplain"),
    ('matchgevonden2', ['pass', '1♥', 'pass'], 12, 4, 3, 4, 2, '4Hs',"noexplain"),
    ('voorbereidendklaveren', ['pass'], 12, 4, 4, 3, 2, '1Cs',"noexplain")
    ]

@pytest.mark.parametrize('descr, cb, points, schoppen, harten, ruiten, klaveren, expected, explain', testcases)
def testBidding(descr, cb, points, schoppen, harten, ruiten, klaveren, expected, explain):
    def pretty(s):
        return s.replace("Hs", "♥").replace("Ss", "♠").replace("Ds", "♦").replace("Cs", "♣")
    
    current = [pretty(b) for b in cb]
    assert bids(current, points, schoppen, harten, ruiten, klaveren) == (pretty(expected), explain)

