import re
from typing import Callable

from kivy.storage.jsonstore import JsonStore

from bidding import Bidding
from biddingEncoder import json2Bid, bid2Json
from bidding_tree import bids
from constants import clubs, diamonds, hearts, spades
from uibuilders import colors
from uitleg import uitleg_nl
from datetime import datetime

biddingScreen = 'biddingScreen'
fileChooserScreen = 'fileChooserScreen'
specificationScreen = 'specificationScreen'
adviceScreen = 'adviceScreen'
blankScreen = 'blankScreen'

class Mediator():
    switchTo: Callable[[str], None]
    
    bidding: Bidding = None
    storage = JsonStore('allbids.json')

    advice: str = None
    patternExplanation = re.compile('\n[\t ]+')

    def __init__(self, switchTo):
        self.switchTo = switchTo

    def setBidding(self, bidding: Bidding):
        self.bidding = bidding

    def showAdvice(self):
        cards = self.bidding.nrOfCards
        print("('autogenerated', %s, %d, %d, %d, %d, %d, '???', '???')" % (str(self.bidding.current), self.bidding.nrOfPoints,
                                                                    cards[spades], cards[hearts], cards[diamonds], cards[clubs]))
        (bid, explainTag) = bids(self.bidding.current, self.bidding.nrOfPoints,
                           cards[spades], cards[hearts], cards[diamonds], cards[clubs])
        explanation = uitleg_nl(explainTag).replace("\t","")
        cleaned = re.sub(self.patternExplanation, '\n\n', explanation)
        self.advice = (bid, cleaned)

        self.switchTo(adviceScreen)

    def closeAdvice(self):
        self.switchTo(biddingScreen)

    def editBidding(self, bidding: Bidding):
        self.setBidding(bidding)
        self.switchTo(biddingScreen)

    def closeBidding(self):
        key = "Bidding at " + datetime.now().strftime("%c")
        value = bid2Json(self.bidding)
        self.storage.put(key, bid=value)
        self.switchTo(fileChooserScreen)

    def loadBidding(self, key):
        bidding = json2Bid(self.storage.get(key)['bid'])
        self.editBidding(bidding)

    def deleteBidding(self, key):
        self.storage.delete(key)
        self.switchTo(fileChooserScreen)

    def changeBiddingName(self, key, value):
        if (not self.storage.exists(value)):
            self.storage.put(value, bid=self.storage.get(key)['bid'])
            self.storage.delete(key)
        self.switchTo(fileChooserScreen)